/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedGradesRouteImport } from './routes/_authenticated/grades'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTestingRouteImport } from './routes/_authenticated/testing'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedWeekRouteImport } from './routes/_authenticated/week'
import { Route as WebApiSplatRouteImport } from './routes/web-api.$'
import { Route as AuthenticatedAdministrationSectionRouteImport } from './routes/_authenticated/administration.$section'
import { Route as AuthenticatedGradesSubjectRouteImport } from './routes/_authenticated/grades.$subject'
import { Route as AuthenticatedSettingsSectionRouteImport } from './routes/_authenticated/settings.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestingRoute = AuthenticatedTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeekRoute = AuthenticatedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const WebApiSplatRoute = WebApiSplatRouteImport.update({
  id: '/web-api/$',
  path: '/web-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministrationSectionRoute =
  AuthenticatedAdministrationSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedGradesSubjectRoute =
  AuthenticatedGradesSubjectRouteImport.update({
    id: '/$subject',
    path: '/$subject',
    getParentRoute: () => AuthenticatedGradesRoute,
  } as any)
const AuthenticatedSettingsSectionRoute =
  AuthenticatedSettingsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/classes': typeof AuthenticatedClassesRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/grades': typeof AuthenticatedGradesRouteWithChildren
  '/planner': typeof AuthenticatedPlannerRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/testing': typeof AuthenticatedTestingRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/web-api/$': typeof WebApiSplatRoute
  '/administration/$section': typeof AuthenticatedAdministrationSectionRoute
  '/grades/$subject': typeof AuthenticatedGradesSubjectRoute
  '/settings/$section': typeof AuthenticatedSettingsSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/classes': typeof AuthenticatedClassesRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/grades': typeof AuthenticatedGradesRouteWithChildren
  '/planner': typeof AuthenticatedPlannerRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/testing': typeof AuthenticatedTestingRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/web-api/$': typeof WebApiSplatRoute
  '/administration/$section': typeof AuthenticatedAdministrationSectionRoute
  '/grades/$subject': typeof AuthenticatedGradesSubjectRoute
  '/settings/$section': typeof AuthenticatedSettingsSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/grades': typeof AuthenticatedGradesRouteWithChildren
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/testing': typeof AuthenticatedTestingRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/week': typeof AuthenticatedWeekRoute
  '/web-api/$': typeof WebApiSplatRoute
  '/_authenticated/administration/$section': typeof AuthenticatedAdministrationSectionRoute
  '/_authenticated/grades/$subject': typeof AuthenticatedGradesSubjectRoute
  '/_authenticated/settings/$section': typeof AuthenticatedSettingsSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administration'
    | '/classes'
    | '/friends'
    | '/grades'
    | '/planner'
    | '/settings'
    | '/testing'
    | '/timetable'
    | '/today'
    | '/week'
    | '/web-api/$'
    | '/administration/$section'
    | '/grades/$subject'
    | '/settings/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/administration'
    | '/classes'
    | '/friends'
    | '/grades'
    | '/planner'
    | '/settings'
    | '/testing'
    | '/timetable'
    | '/today'
    | '/week'
    | '/web-api/$'
    | '/administration/$section'
    | '/grades/$subject'
    | '/settings/$section'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/administration'
    | '/_authenticated/classes'
    | '/_authenticated/friends'
    | '/_authenticated/grades'
    | '/_authenticated/planner'
    | '/_authenticated/settings'
    | '/_authenticated/testing'
    | '/_authenticated/timetable'
    | '/_authenticated/today'
    | '/_authenticated/week'
    | '/web-api/$'
    | '/_authenticated/administration/$section'
    | '/_authenticated/grades/$subject'
    | '/_authenticated/settings/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  WebApiSplatRoute: typeof WebApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/testing': {
      id: '/_authenticated/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof AuthenticatedTestingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/web-api/$': {
      id: '/web-api/$'
      path: '/web-api/$'
      fullPath: '/web-api/$'
      preLoaderRoute: typeof WebApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administration/$section': {
      id: '/_authenticated/administration/$section'
      path: '/$section'
      fullPath: '/administration/$section'
      preLoaderRoute: typeof AuthenticatedAdministrationSectionRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/grades/$subject': {
      id: '/_authenticated/grades/$subject'
      path: '/$subject'
      fullPath: '/grades/$subject'
      preLoaderRoute: typeof AuthenticatedGradesSubjectRouteImport
      parentRoute: typeof AuthenticatedGradesRoute
    }
    '/_authenticated/settings/$section': {
      id: '/_authenticated/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AuthenticatedSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedAdministrationRouteChildren {
  AuthenticatedAdministrationSectionRoute: typeof AuthenticatedAdministrationSectionRoute
}

const AuthenticatedAdministrationRouteChildren: AuthenticatedAdministrationRouteChildren =
  {
    AuthenticatedAdministrationSectionRoute:
      AuthenticatedAdministrationSectionRoute,
  }

const AuthenticatedAdministrationRouteWithChildren =
  AuthenticatedAdministrationRoute._addFileChildren(
    AuthenticatedAdministrationRouteChildren,
  )

interface AuthenticatedGradesRouteChildren {
  AuthenticatedGradesSubjectRoute: typeof AuthenticatedGradesSubjectRoute
}

const AuthenticatedGradesRouteChildren: AuthenticatedGradesRouteChildren = {
  AuthenticatedGradesSubjectRoute: AuthenticatedGradesSubjectRoute,
}

const AuthenticatedGradesRouteWithChildren =
  AuthenticatedGradesRoute._addFileChildren(AuthenticatedGradesRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsSectionRoute: typeof AuthenticatedSettingsSectionRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsSectionRoute: AuthenticatedSettingsSectionRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRouteWithChildren
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRouteWithChildren
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTestingRoute: typeof AuthenticatedTestingRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWeekRoute: typeof AuthenticatedWeekRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministrationRoute:
    AuthenticatedAdministrationRouteWithChildren,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedGradesRoute: AuthenticatedGradesRouteWithChildren,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTestingRoute: AuthenticatedTestingRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWeekRoute: AuthenticatedWeekRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  WebApiSplatRoute: WebApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
